---
- name: Demo Playbook
  hosts: localhost
  remote_user: root
  gather_facts: no
  force_handlers: no
  tasks:
    - name: flag2
      debug:
        msg: "{{ ftwo }}"

    - name: flag3
      debug:
        msg: "{{ fthree }}"

    - name: flag4
      debug:
        msg: "{{ ffour | default('UNDEFINED') }}"

    - name: flag5
      debug:
        msg: "{{ ffive }}"

    - name: flag6
      debug:
        msg: "{{ fsix | default('UNDEFINED') }}"
